"""Plugin UI files generation
"""

from pathlib import Path


# Content of 'ui_options.ui' file
UI_OPTIONS_UI = """<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>PlaygroundOptionsPage</class>
 <widget class="QWidget" name="PlaygroundOptionsPage">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>602</width>
    <height>555</height>
   </rect>
  </property>
  <layout class="QVBoxLayout">
   <property name="spacing">
    <number>6</number>
   </property>
   <property name="leftMargin">
    <number>9</number>
   </property>
   <property name="topMargin">
    <number>9</number>
   </property>
   <property name="rightMargin">
    <number>9</number>
   </property>
   <property name="bottomMargin">
    <number>9</number>
   </property>
   <item>
    <widget class="QGroupBox" name="groupBox">
     <property name="title">
      <string>title.playground_options</string>
     </property>
     <layout class="QVBoxLayout">
      <property name="spacing">
       <number>2</number>
      </property>
      <property name="leftMargin">
       <number>9</number>
      </property>
      <property name="topMargin">
       <number>9</number>
      </property>
      <property name="rightMargin">
       <number>9</number>
      </property>
      <property name="bottomMargin">
       <number>9</number>
      </property>
      <item>
       <widget class="QFrame" name="xqaf_compression_disabled_note">
        <property name="frameShape">
         <enum>QFrame::NoFrame</enum>
        </property>
        <layout class="QVBoxLayout" name="verticalLayout_3">
         <property name="spacing">
          <number>0</number>
         </property>
         <property name="leftMargin">
          <number>0</number>
         </property>
         <property name="topMargin">
          <number>0</number>
         </property>
         <property name="rightMargin">
          <number>0</number>
         </property>
         <property name="bottomMargin">
          <number>0</number>
         </property>
         <item>
          <widget class="QFrame" name="frame_2">
           <property name="styleSheet">
            <string notr="true">QFrame { background-color: #ffc107; color: black }
QCheckBox { color: black }</string>
           </property>
           <property name="frameShape">
            <enum>QFrame::NoFrame</enum>
           </property>
           <layout class="QVBoxLayout" name="verticalLayout_2">
            <item>
             <widget class="QLabel" name="label">
              <property name="text">
               <string>label.disclaimer</string>
              </property>
              <property name="wordWrap">
               <bool>true</bool>
              </property>
             </widget>
            </item>
           </layout>
          </widget>
         </item>
         <item>
          <spacer name="verticalSpacer_2">
           <property name="orientation">
            <enum>Qt::Vertical</enum>
           </property>
           <property name="sizeType">
            <enum>QSizePolicy::Fixed</enum>
           </property>
           <property name="sizeHint" stdset="0">
            <size>
             <width>1</width>
             <height>6</height>
            </size>
           </property>
          </spacer>
         </item>
        </layout>
       </widget>
      </item>
      <item>
       <widget class="QCheckBox" name="run_image_processor">
        <property name="text">
         <string>label.run_image_processor</string>
        </property>
       </widget>
      </item>
     </layout>
    </widget>
   </item>
   <item>
    <spacer name="verticalSpacer">
     <property name="orientation">
      <enum>Qt::Vertical</enum>
     </property>
     <property name="sizeHint" stdset="0">
      <size>
       <width>20</width>
       <height>40</height>
      </size>
     </property>
    </spacer>
   </item>
  </layout>
 </widget>
 <resources/>
 <connections/>
</ui>
"""

# Content of 'ui_options.py' file
UI_OPTIONS_PY = """# Form implementation generated from reading ui file 'ui_options.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlaygroundOptionsPage(object):
    def setupUi(self, PlaygroundOptionsPage):
        PlaygroundOptionsPage.setObjectName("PlaygroundOptionsPage")
        PlaygroundOptionsPage.resize(602, 555)
        self.vboxlayout = QtWidgets.QVBoxLayout(PlaygroundOptionsPage)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtWidgets.QGroupBox(parent=PlaygroundOptionsPage)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.xqaf_compression_disabled_note = QtWidgets.QFrame(parent=self.groupBox)
        self.xqaf_compression_disabled_note.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.xqaf_compression_disabled_note.setObjectName("xqaf_compression_disabled_note")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.xqaf_compression_disabled_note)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.xqaf_compression_disabled_note)
        self.frame_2.setStyleSheet("QFrame { background-color: #ffc107; color: black }\\n"
"QCheckBox { color: black }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(1, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.vboxlayout1.addWidget(self.xqaf_compression_disabled_note)
        self.run_image_processor = QtWidgets.QCheckBox(parent=self.groupBox)
        self.run_image_processor.setObjectName("run_image_processor")
        self.vboxlayout1.addWidget(self.run_image_processor)
        self.vboxlayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(PlaygroundOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(PlaygroundOptionsPage)

    def retranslateUi(self, PlaygroundOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("PlaygroundOptionsPage", "title.playground_options"))
        self.label.setText(_translate("PlaygroundOptionsPage", "label.disclaimer"))
        self.run_image_processor.setText(_translate("PlaygroundOptionsPage", "label.run_image_processor"))
"""


def write_ui(plugin_dir: Path) -> str | None:
    """Write the ui_options.ui and ui_options.py files.

    Args:
        plugin_dir (str): Plugin directory

    Returns:
        str | None: Error message or None if successful
    """
    for filename, text in [('ui_options.ui', UI_OPTIONS_UI), ('ui_options.py', UI_OPTIONS_PY)]:
        try:
            (plugin_dir / filename).write_text(text, encoding='utf8')
        except Exception as e:
            return f"Error writing '{filename}': {e}"

    return None
